name: movieverse
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  http: ^1.2.2
  flutter_dotenv: ^5.0.2
  url_launcher: ^6.1.14
  provider: ^6.0.3
  cloud_firestore: ^5.6.2
  firebase_auth: ^5.4.1
  firebase_core: ^3.10.1
  firebase_storage: ^12.4.1
  image_picker: ^1.0.4
  cupertino_icons: ^1.0.8
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/virtual1.png
    - .env
